name: telemetrygen
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+*'
  # merge_group:
  # pull_request:
env:
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

# Do not cancel this workflow on main. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16616
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-dev:
    runs-on: ubuntu-20.04-ppc64le
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
          architecture: ppc64le
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v2
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Setup make
        run: sudo apt install -qy make
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=ppc64le make telemetrygen
          cp bin/telemetrygen_* cmd/telemetrygen/
      - name: Build telemetrygen
        uses: docker/build-push-action@v3
        with:
          context: cmd/telemetrygen
          push: false
          tags: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:dev
          platforms: linux/ppc64le

  publish-latest:
    runs-on: ubuntu-20.04-ppc64le
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
          architecture: ppc64le
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v2
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup make
        run: sudo apt install -qy make
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=ppc64le make telemetrygen
          cp bin/telemetrygen_* cmd/telemetrygen/
      - name: Push telemetrygen to Github packages
        uses: docker/build-push-action@v3
        with:
          context: cmd/telemetrygen
          push: true
          tags: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          platforms: linux/ppc64le

  publish-stable:
    runs-on: ubuntu-20.04-ppc64le
    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
          architecture: ppc64le
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v2
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set Release Tag
        id: github_tag
        run: ./.github/workflows/scripts/set_release_tag.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup make
        run: sudo apt install -qy make
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=ppc64le make telemetrygen
          cp bin/telemetrygen_* cmd/telemetrygen/
      - name: Push telemetrygen to Github packages
        uses: docker/build-push-action@v3
        with:
          context: cmd/telemetrygen
          push: true
          tags: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:${{ steps.github_tag.outputs.tag }}
          platforms: linux/ppc64le
